# Generated by Django 6.0.3 on 2026-03-09 02:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id_categoria', models.AutoField(db_column='ID_Categoria', primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(db_column='Nombre_categoria', max_length=100)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id_cliente', models.AutoField(db_column='ID_Cliente', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('dirreccion', models.CharField(blank=True, db_column='Dirreccion', max_length=255, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id_compra', models.AutoField(db_column='ID_Compra', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'db_table': 'Compras',
            },
        ),
        migrations.CreateModel(
            name='Materiales',
            fields=[
                ('id_materiales', models.AutoField(db_column='ID_Materiales', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('tipo', models.CharField(blank=True, db_column='Tipo', max_length=100, null=True)),
                ('stock', models.IntegerField(db_column='Stock', default=0)),
                ('unidad_medida', models.CharField(blank=True, db_column='Unidad_medida', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'db_table': 'Materiales',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_proveedores', models.AutoField(db_column='ID_Proveedores', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('telefono', models.CharField(blank=True, db_column='Telefono', max_length=20, null=True)),
                ('direccion', models.CharField(blank=True, db_column='Direccion', max_length=255, null=True)),
                ('correo', models.CharField(blank=True, db_column='Correo', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'Proveedor',
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(db_column='ID_Usuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=100)),
                ('apellido', models.CharField(db_column='Apellido', max_length=100)),
                ('usuario', models.CharField(db_column='Usuario', max_length=100, unique=True)),
                ('contrasenia', models.CharField(db_column='Contrasenia', max_length=255)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('vendedor', 'Vendedor'), ('cliente', 'Cliente')], db_column='Rol', default='cliente', max_length=20)),
                ('eliminado', models.BooleanField(db_column='Eliminado', default=False)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='DetalleCompra',
            fields=[
                ('id_decompras', models.AutoField(db_column='ID_DeCompras', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='Precio_unitario', decimal_places=2, max_digits=10)),
                ('id_compra', models.ForeignKey(db_column='ID_Compra', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.compras')),
                ('id_material', models.ForeignKey(db_column='ID_Material', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_compra', to='tienda.materiales')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalles de Compra',
                'db_table': 'Detalle_Compra',
            },
        ),
        migrations.CreateModel(
            name='Muebles',
            fields=[
                ('id_muebles', models.AutoField(db_column='ID_muebles', primary_key=True, serialize=False)),
                ('nombre', models.CharField(db_column='Nombre', max_length=200)),
                ('descripcion', models.TextField(blank=True, db_column='Descripcion', null=True)),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(db_column='Stock', default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='muebles/')),
                ('id_categoria', models.ForeignKey(db_column='ID_Categoria', on_delete=django.db.models.deletion.CASCADE, related_name='muebles', to='tienda.categorias')),
            ],
            options={
                'verbose_name': 'Mueble',
                'verbose_name_plural': 'Muebles',
                'db_table': 'Muebles',
            },
        ),
        migrations.AddField(
            model_name='compras',
            name='id_proveedor',
            field=models.ForeignKey(db_column='ID_Proveedor', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='tienda.proveedor'),
        ),
        migrations.AddField(
            model_name='compras',
            name='id_usuario',
            field=models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='compras', to='tienda.usuarios'),
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id_venta', models.AutoField(db_column='ID_Venta', primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_column='Fecha')),
                ('total', models.DecimalField(db_column='Total', decimal_places=2, default=0, max_digits=10)),
                ('id_cliente', models.ForeignKey(db_column='ID_Cliente', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='tienda.clientes')),
                ('id_usuario', models.ForeignKey(db_column='ID_Usuario', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='tienda.usuarios')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
            },
        ),
        migrations.CreateModel(
            name='DetallesVentas',
            fields=[
                ('id_deventas', models.AutoField(db_column='ID_DeVentas', primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio_unitario', models.DecimalField(db_column='Precio_unitario', decimal_places=2, max_digits=10)),
                ('id_muebles', models.ForeignKey(db_column='ID_Muebles', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_ventas', to='tienda.muebles')),
                ('id_ventas', models.ForeignKey(db_column='ID_Ventas', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tienda.ventas')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'Detalles_ventas',
            },
        ),
    ]
